#!/usr/bin/env python3
"""
"""

from dotplug import console
from dotplug.console import ColorPair


def display():
    for row in range(6):
        t = console.TaskBar(str(row), 12, row + 4)
        t.message.write('Hello', color=ColorPair.BLUE)
        t.status.done()


if __name__ == '__main__':
    with console.ncurses() as stdscr:
        display()
        input("")
